version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      types:
        patterns:
          - '@types/*'
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
